# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd7070274dc66aab12e48c068f547cdef63217c4327910b2bcfe0a77f76790f124ddc9ff7d01aecbb31412d73d153cab0dc72f0ac3a1029338d38da2e806cce0

test:
  secret_key_base: 219cabafd46b45fede7d325c1a5176b029228879e49092d662a45c37cab71ca27d20cb5843cc7632eb6b5074e274f19a4f414b6963d29e0a9609bb1e1c5e40dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
